### ISSUE TITLE
Company background

### ISSUE THREAD

**Issue by Pitso-Paballo** [Pitso-Paballo/Innovate-Six#6]
Give the background of the company

**Comment by SimphiweMecheall** [comment]
**Company Background:**

Our company consists of five members who come from different parts of the country, and its formation was based on the idea that we want to improve early childhood literacy. Most of us grew up in families with limited incomes, where our parents could not afford to provide us with special classes in English and Maths or tutors who could help us develop proper skills. This made us realize how important early language development is and how sometimes receiving a proper education is an ideal that remains out of reach simply because of the financial standing of a particular family.
What we wanted was the solution that would guarantee every child, regardless of their background, the equal right to develop good reading, pronunciation skills and be good with numbers while still very young. Our AI-powered tool was envisioned with this dream in mind: a free, easy-to-use learning plugin already empowering toddlers with individual reading support to read loudly and correctly pronounce all types of words. By making this tool free, we hope to break down the barriers preventing many children from accessing quality early education resources.

We went with AI technology because, with it, the solution can scale and adapt. We are able to implement something that reaches a very big number of children, without necessarily having to use very expensive infrastructure. This tool ensures toddlers from walks of life get help to become confident.
